services:
  backend:
    image: creep-tube:3
    ports:
      - "8080:8080"
  frontend:
    image: creep-tube-ui:1
    environment:
      - 'CHOKIDAR_USEPOLLING=true'
      - 'WATCHPACK_POLLING=true'
      - 'WDS_SOCKET_HOST=127.0.0.1'
    volumes:
      - C:\Users\alexey\IdeaProjects\creep-tube-ui:/creep-tube-ui
    ports:
      - "3000:3000"